language: python

matrix:
  # This will launch a separate build for each Python version you add
  # Feel free to add extra environment variables as needed
  include:
    - python: 3.5

before_install:
  - sudo apt-get update
  # Install the latest version of Miniconda
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  # Create a new environment
  - conda create -q -n pyfbow_test_env python=$TRAVIS_PYTHON_VERSION opencv=3.3.* numpy boost py-boost cmake unzip
  - conda activate pyfbow_test_env
  - chmod +x build_and_install_pyfbow.sh
  - ./build_and_install_pyfbow.sh

script:
  - mkdir data
  - cd data
  - wget https://s3.eu-central-1.amazonaws.com/avg-kitti/raw_data/2011_09_28_drive_0047/2011_09_28_drive_0047_sync.zip
  - unzip 2011_09_28_drive_0047_sync.zip
  - cd ..
  - echo "$(pwd)/build" > $CONDA_PREFIX/lib/python$TRAVIS_PYTHON_VERSION/site-packages/pyfbow.pth
  - python -c "import pyfbow"
  - python utils/create_vocabulary.py data/2011_09_28/2011_09_28_drive_0047_sync/image_00/data/ -o test_vocab.bin
