language: python

matrix:
  # This will launch a separate build for each Python version you add
  # Feel free to add extra environment variables as needed
  include:
    - python: 3.5
    #- python: 3.8

before_install:
  # Install the latest version of Miniconda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda  # Update CONDA without command line prompt

install:
  # Create a new environment
  - conda create --yes -n pyfbow_test_env python=$TRAVIS_PYTHON_VERSION opencv=3.3.* numpy boost
  - source activate pyfbow_test_env


script:
  - chmod +x build_and_install_pyfbow.sh
  - ./chmod +x build_and_install_pyfbow.sh
